/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.quine.slibj;

public class FaceDetection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FaceDetection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FaceDetection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        slibjJNI.delete_FaceDetection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FaceDetection(String model) {
    this(slibjJNI.new_FaceDetection(model), true);
  }

  public String largestFace(String path, long cropSize, String outpath) {
    return slibjJNI.FaceDetection_largestFace__SWIG_0(swigCPtr, this, path, cropSize, outpath);
  }

  public String largestFace(String path, long cropSize) {
    return slibjJNI.FaceDetection_largestFace__SWIG_1(swigCPtr, this, path, cropSize);
  }

}
