/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.quine.slibj;

public class ImageConversion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImageConversion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageConversion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        slibjJNI.delete_ImageConversion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImageConversion() {
    this(slibjJNI.new_ImageConversion(), true);
  }

  public void image2Array(String imgpath, String outpath, int size) {
    slibjJNI.ImageConversion_image2Array(swigCPtr, this, imgpath, outpath, size);
  }

}
