/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.quine.slibj;

public class ObjectModelVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjectModelVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectModelVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        slibjJNI.delete_ObjectModelVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ObjectModelVector() {
    this(slibjJNI.new_ObjectModelVector__SWIG_0(), true);
  }

  public ObjectModelVector(long n) {
    this(slibjJNI.new_ObjectModelVector__SWIG_1(n), true);
  }

  public long size() {
    return slibjJNI.ObjectModelVector_size(swigCPtr, this);
  }

  public long capacity() {
    return slibjJNI.ObjectModelVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    slibjJNI.ObjectModelVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return slibjJNI.ObjectModelVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    slibjJNI.ObjectModelVector_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_dlib__full_object_detection x) {
    slibjJNI.ObjectModelVector_add(swigCPtr, this, SWIGTYPE_p_dlib__full_object_detection.getCPtr(x));
  }

  public SWIGTYPE_p_dlib__full_object_detection get(int i) {
    return new SWIGTYPE_p_dlib__full_object_detection(slibjJNI.ObjectModelVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_dlib__full_object_detection val) {
    slibjJNI.ObjectModelVector_set(swigCPtr, this, i, SWIGTYPE_p_dlib__full_object_detection.getCPtr(val));
  }

}
