/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.quine.slibj;

public class RectangleVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RectangleVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RectangleVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        slibjJNI.delete_RectangleVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RectangleVector() {
    this(slibjJNI.new_RectangleVector__SWIG_0(), true);
  }

  public RectangleVector(long n) {
    this(slibjJNI.new_RectangleVector__SWIG_1(n), true);
  }

  public long size() {
    return slibjJNI.RectangleVector_size(swigCPtr, this);
  }

  public long capacity() {
    return slibjJNI.RectangleVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    slibjJNI.RectangleVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return slibjJNI.RectangleVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    slibjJNI.RectangleVector_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_dlib__rectangle x) {
    slibjJNI.RectangleVector_add(swigCPtr, this, SWIGTYPE_p_dlib__rectangle.getCPtr(x));
  }

  public SWIGTYPE_p_dlib__rectangle get(int i) {
    return new SWIGTYPE_p_dlib__rectangle(slibjJNI.RectangleVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_dlib__rectangle val) {
    slibjJNI.RectangleVector_set(swigCPtr, this, i, SWIGTYPE_p_dlib__rectangle.getCPtr(val));
  }

}
